import 'dart:io';
import 'dart:ui';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../auctions/models/auction_model.dart';
import '../auctions/repositories/auction_repository.dart';
import '../auctions/controllers/auction_controller.dart';
import '../auth/controllers/auth_controller.dart';

class CreateListingScreen extends ConsumerStatefulWidget {
  const CreateListingScreen({super.key});

  @override
  ConsumerState<CreateListingScreen> createState() => _CreateListingScreenState();
}

class _CreateListingScreenState extends ConsumerState<CreateListingScreen> {
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _startingPriceController = TextEditingController();
  String? _selectedCategory;
  String _selectedDuration = '7d';
  bool _isLoading = false;
  bool _acceptedTerms = false;
  
  final _picker = ImagePicker();
  List<XFile> _selectedImages = [];

  final List<String> _categories = ['Watches & Jewelry', 'Art & Collectibles', 'Fashion & Accessories', 'Electronics', 'Real Estate'];
  final List<String> _durations = ['24h', '7d', '14d'];

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _startingPriceController.dispose();
    super.dispose();
  }

  Future<void> _pickImages() async {
    try {
      final List<XFile> images = await _picker.pickMultiImage(imageQuality: 80);
      if (images.isNotEmpty) {
        setState(() {
          if (_selectedImages.length + images.length > 10) {
            _selectedImages.addAll(images.take(10 - _selectedImages.length));
            ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Maximum 10 images allowed.')));
          } else {
            _selectedImages.addAll(images);
          }
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error picking images: $e')));
      }
    }
  }

  void _removeImage(int index) {
    setState(() {
      _selectedImages.removeAt(index);
    });
  }

  Future<void> _publishListing() async {
    if (_titleController.text.isEmpty || _startingPriceController.text.isEmpty || _selectedCategory == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please fill all required fields.')));
      return;
    }
    if (_selectedImages.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select at least one photo.')));
      return;
    }
    if (!_acceptedTerms) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please accept the terms to continue.')));
      return;
    }

    setState(() => _isLoading = true);
    try {
      final user = ref.read(authControllerProvider).value;
      if (user == null) throw Exception('Not logged in');

      String? imageUrl;
      List<String> uploadedUrls = [];
      if (_selectedImages.isNotEmpty) {
        for (var img in _selectedImages) {
          final bytes = await img.readAsBytes();
          final url = await ref.read(auctionRepositoryProvider).uploadImage(bytes, img.name);
          uploadedUrls.add(url);
        }
        if (uploadedUrls.isNotEmpty) imageUrl = uploadedUrls.first;
      }

      int days = 7;
      if (_selectedDuration == '24h') days = 1;
      if (_selectedDuration == '14d') days = 14;
      final endTime = DateTime.now().add(Duration(days: days));

      final auction = AuctionModel(
        id: '', // Will be generated by Appwrite
        title: _titleController.text,
        subtitle: _selectedCategory!,
        category: _selectedCategory!,
        description: _descriptionController.text.isNotEmpty ? _descriptionController.text : 'No description provided.',
        imageEmoji: '📦',
        imageUrl: imageUrl,
        imageUrls: uploadedUrls,
        currentBid: int.tryParse(_startingPriceController.text) ?? 0,
        totalBids: 0,
        status: 'active',
        endTime: endTime,
        sellerId: user.$id,
        sellerName: user.name,
      );

      await ref.read(auctionRepositoryProvider).createAuction(auction);

      ref.invalidate(recentAuctionsProvider);
      ref.invalidate(trendingAuctionsProvider);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('🎉 Listing published successfully!'),
            backgroundColor: const Color(0xFF006c49),
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
          ),
        );
        context.go('/home');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Widget _buildGlassPanel({required Widget child}) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.7),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.white.withOpacity(0.3)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.02),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(16),
        child: BackdropFilter(
          filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: child,
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(IconData icon, String title) {
    return Row(
      children: [
        Icon(icon, color: const Color(0xFF4648d4), size: 24),
        const SizedBox(width: 8),
        Text(
          title,
          style: const TextStyle(
            fontFamily: 'Manrope',
            fontSize: 24,
            fontWeight: FontWeight.w700,
            color: Color(0xFF1b1b23),
          ),
        ),
      ],
    );
  }

  Widget _buildInputLabel(String label) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 4.0),
      child: Text(
        label,
        style: const TextStyle(
          fontFamily: 'Inter',
          fontSize: 14,
          fontWeight: FontWeight.w600,
          color: Color(0xFF464554),
        ),
      ),
    );
  }

  InputDecoration _inputDecoration(String hint, {Widget? prefixIcon}) {
    return InputDecoration(
      hintText: hint,
      hintStyle: const TextStyle(color: Color(0xFF767586), fontFamily: 'Inter'),
      prefixIcon: prefixIcon,
      filled: true,
      fillColor: Colors.white.withOpacity(0.5),
      contentPadding: const EdgeInsets.all(16),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: BorderSide(color: Colors.white.withOpacity(0.4)),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: BorderSide(color: Colors.white.withOpacity(0.4)),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: const BorderSide(color: Color(0xFF6366F1), width: 1.5),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFfcf8ff),
      body: Stack(
        children: [
          // Decorative Blobs
          Positioned(
            top: -100,
            right: -100,
            child: Container(
              width: 400,
              height: 400,
              decoration: BoxDecoration(
                color: const Color(0xFF4648d4).withOpacity(0.1),
                shape: BoxShape.circle,
              ),
              child: BackdropFilter(
                filter: ImageFilter.blur(sigmaX: 100, sigmaY: 100),
                child: Container(color: Colors.transparent),
              ),
            ),
          ),
          Positioned(
            bottom: -100,
            left: -100,
            child: Container(
              width: 400,
              height: 400,
              decoration: BoxDecoration(
                color: const Color(0xFF006c49).withOpacity(0.05),
                shape: BoxShape.circle,
              ),
              child: BackdropFilter(
                filter: ImageFilter.blur(sigmaX: 100, sigmaY: 100),
                child: Container(color: Colors.transparent),
              ),
            ),
          ),
          
          SafeArea(
            child: CustomScrollView(
              slivers: [
                SliverAppBar(
                  backgroundColor: Colors.white.withOpacity(0.7),
                  pinned: true,
                  elevation: 0,
                  leading: IconButton(
                    icon: const Icon(Icons.close_rounded, color: Color(0xFF1b1b23)),
                    onPressed: () {
                      if (context.canPop()) {
                        context.pop();
                      } else {
                        context.go('/home');
                      }
                    },
                  ),
                  flexibleSpace: ClipRRect(
                    child: BackdropFilter(
                      filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
                      child: Container(
                        decoration: BoxDecoration(
                          border: Border(bottom: BorderSide(color: Colors.white.withOpacity(0.3))),
                        ),
                      ),
                    ),
                  ),
                  title: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      const Icon(Icons.gavel, color: Color(0xFF4648d4), size: 24),
                      const SizedBox(width: 8),
                      const Text(
                        'SnapBid',
                        style: TextStyle(
                          fontFamily: 'Manrope',
                          fontSize: 20,
                          fontWeight: FontWeight.w800,
                          color: Color(0xFF4648d4),
                          letterSpacing: -0.5,
                        ),
                      ),
                    ],
                  ),
                  centerTitle: true,
                ),
                SliverPadding(
                  padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 32.0),
                  sliver: SliverList(
                    delegate: SliverChildListDelegate([
                      const Text(
                        'Create New Listing',
                        style: TextStyle(
                          fontFamily: 'Manrope',
                          fontSize: 32,
                          fontWeight: FontWeight.w700,
                          color: Color(0xFF1b1b23),
                        ),
                      ),
                      const SizedBox(height: 8),
                      const Text(
                        'Fill in the details to showcase your item to thousands of bidders.',
                        style: TextStyle(
                          fontFamily: 'Inter',
                          fontSize: 16,
                          color: Color(0xFF464554),
                        ),
                      ),
                      const SizedBox(height: 32),

                      // Section 1: Photos
                      _buildGlassPanel(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                _buildSectionTitle(Icons.photo_library_outlined, 'Photos'),
                                Text(
                                  '${_selectedImages.length} / 10 Images',
                                  style: const TextStyle(
                                    fontFamily: 'Inter',
                                    fontSize: 14,
                                    color: Color(0xFF767586),
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 16),
                            if (_selectedImages.isEmpty)
                              GestureDetector(
                                onTap: _pickImages,
                                child: Container(
                                  height: 200,
                                  width: double.infinity,
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.5),
                                    borderRadius: BorderRadius.circular(8),
                                    border: Border.all(
                                      color: const Color(0xFFc7c4d7),
                                      style: BorderStyle.solid,
                                      width: 2,
                                    ),
                                  ),
                                  child: const Column(
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    children: [
                                      Icon(Icons.add_photo_alternate_outlined, size: 40, color: Color(0xFF767586)),
                                      SizedBox(height: 8),
                                      Text(
                                        'Add Main Photo',
                                        style: TextStyle(
                                          fontFamily: 'Inter',
                                          fontSize: 14,
                                          fontWeight: FontWeight.w600,
                                          color: Color(0xFF767586),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              )
                            else
                              Column(
                                children: [
                                  Container(
                                    height: 200,
                                    width: double.infinity,
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(8),
                                      image: DecorationImage(
                                        image: kIsWeb
                                            ? NetworkImage(_selectedImages.first.path)
                                            : FileImage(File(_selectedImages.first.path)) as ImageProvider,
                                        fit: BoxFit.cover,
                                      ),
                                    ),
                                    child: Align(
                                      alignment: Alignment.topRight,
                                      child: IconButton(
                                        icon: Container(
                                          padding: const EdgeInsets.all(4),
                                          decoration: const BoxDecoration(color: Colors.black54, shape: BoxShape.circle),
                                          child: const Icon(Icons.close, color: Colors.white, size: 16),
                                        ),
                                        onPressed: () => _removeImage(0),
                                      ),
                                    ),
                                  ),
                                  if (_selectedImages.length > 1 || _selectedImages.length < 10)
                                    Padding(
                                      padding: const EdgeInsets.only(top: 16.0),
                                      child: SizedBox(
                                        height: 80,
                                        child: ListView.builder(
                                          scrollDirection: Axis.horizontal,
                                          itemCount: (_selectedImages.length - 1) + (_selectedImages.length < 10 ? 1 : 0),
                                          itemBuilder: (context, index) {
                                            if (index == _selectedImages.length - 1 && _selectedImages.length < 10) {
                                              return GestureDetector(
                                                onTap: _pickImages,
                                                child: Container(
                                                  width: 80,
                                                  margin: const EdgeInsets.only(right: 8),
                                                  decoration: BoxDecoration(
                                                    color: Colors.white.withOpacity(0.5),
                                                    borderRadius: BorderRadius.circular(8),
                                                    border: Border.all(color: const Color(0xFFc7c4d7), width: 2),
                                                  ),
                                                  child: const Icon(Icons.add, color: Color(0xFF767586)),
                                                ),
                                              );
                                            }
                                            final imgIndex = index + 1;
                                            return Container(
                                              width: 80,
                                              margin: const EdgeInsets.only(right: 8),
                                              decoration: BoxDecoration(
                                                borderRadius: BorderRadius.circular(8),
                                                image: DecorationImage(
                                                  image: kIsWeb
                                                      ? NetworkImage(_selectedImages[imgIndex].path)
                                                      : FileImage(File(_selectedImages[imgIndex].path)) as ImageProvider,
                                                  fit: BoxFit.cover,
                                                ),
                                              ),
                                              child: Align(
                                                alignment: Alignment.topRight,
                                                child: GestureDetector(
                                                  onTap: () => _removeImage(imgIndex),
                                                  child: Container(
                                                    margin: const EdgeInsets.all(4),
                                                    padding: const EdgeInsets.all(2),
                                                    decoration: const BoxDecoration(color: Colors.black54, shape: BoxShape.circle),
                                                    child: const Icon(Icons.close, color: Colors.white, size: 12),
                                                  ),
                                                ),
                                              ),
                                            );
                                          },
                                        ),
                                      ),
                                    ),
                                ],
                              ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),

                      // Section 2: Item Basics
                      _buildGlassPanel(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _buildSectionTitle(Icons.edit_note_outlined, 'Item Basics'),
                            const SizedBox(height: 24),
                            _buildInputLabel('Listing Title'),
                            TextField(
                              controller: _titleController,
                              style: const TextStyle(fontFamily: 'Inter', fontSize: 16, color: Color(0xFF1b1b23)),
                              decoration: _inputDecoration('e.g. Rare 1964 Vintage Chronograph'),
                            ),
                            const SizedBox(height: 16),
                            _buildInputLabel('Category'),
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 16),
                              decoration: BoxDecoration(
                                color: Colors.white.withOpacity(0.5),
                                borderRadius: BorderRadius.circular(8),
                                border: Border.all(color: Colors.white.withOpacity(0.4)),
                              ),
                              child: DropdownButtonHideUnderline(
                                child: DropdownButton<String>(
                                  value: _selectedCategory,
                                  hint: const Text('Select a category', style: TextStyle(color: Color(0xFF767586), fontFamily: 'Inter')),
                                  isExpanded: true,
                                  icon: const Icon(Icons.expand_more_rounded, color: Color(0xFF767586)),
                                  items: _categories.map((c) => DropdownMenuItem(value: c, child: Text(c, style: const TextStyle(fontFamily: 'Inter', color: Color(0xFF1b1b23))))).toList(),
                                  onChanged: (v) => setState(() => _selectedCategory = v),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),

                      // Section 3: Description
                      _buildGlassPanel(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _buildSectionTitle(Icons.description_outlined, 'Description'),
                            const SizedBox(height: 16),
                            _buildInputLabel('Item Details'),
                            TextField(
                              controller: _descriptionController,
                              maxLines: 5,
                              style: const TextStyle(fontFamily: 'Inter', fontSize: 16, color: Color(0xFF1b1b23)),
                              decoration: _inputDecoration('Describe your item in detail...'),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),

                      // Section 4: Auction Settings
                      _buildGlassPanel(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _buildSectionTitle(Icons.payments_outlined, 'Auction Settings'),
                            const SizedBox(height: 24),
                            _buildInputLabel('Starting Price (\$)'),
                            TextField(
                              controller: _startingPriceController,
                              keyboardType: TextInputType.number,
                              style: const TextStyle(fontFamily: 'Inter', fontSize: 16, color: Color(0xFF1b1b23)),
                              decoration: _inputDecoration('0.00', prefixIcon: const Padding(
                                padding: EdgeInsets.only(left: 16.0, right: 8.0),
                                child: Text('\$', style: TextStyle(fontFamily: 'Inter', fontSize: 16, fontWeight: FontWeight.bold, color: Color(0xFF767586))),
                              )).copyWith(prefixIconConstraints: const BoxConstraints(minWidth: 0, minHeight: 0)),
                            ),
                            const SizedBox(height: 16),
                            _buildInputLabel('Auction Duration'),
                            Container(
                              padding: const EdgeInsets.all(4),
                              decoration: BoxDecoration(
                                color: const Color(0xFFefecf8),
                                borderRadius: BorderRadius.circular(12),
                              ),
                              child: Row(
                                children: _durations.map((d) {
                                  final isSelected = _selectedDuration == d;
                                  return Expanded(
                                    child: GestureDetector(
                                      onTap: () => setState(() => _selectedDuration = d),
                                      child: Container(
                                        padding: const EdgeInsets.symmetric(vertical: 12),
                                        decoration: BoxDecoration(
                                          color: isSelected ? Colors.white : Colors.transparent,
                                          borderRadius: BorderRadius.circular(8),
                                          boxShadow: isSelected ? [BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 4, offset: const Offset(0, 2))] : null,
                                        ),
                                        child: Center(
                                          child: Text(
                                            d,
                                            style: TextStyle(
                                              fontFamily: 'Inter',
                                              fontSize: 14,
                                              fontWeight: FontWeight.w600,
                                              color: isSelected ? const Color(0xFF4648d4) : const Color(0xFF767586),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ),
                                  );
                                }).toList(),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),

                      // Terms and Submission
                      Padding(
                        padding: const EdgeInsets.only(top: 16.0, bottom: 48.0),
                        child: Column(
                          children: [
                            Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Checkbox(
                                  value: _acceptedTerms,
                                  onChanged: (v) => setState(() => _acceptedTerms = v ?? false),
                                  activeColor: const Color(0xFF4648d4),
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                ),
                                const Expanded(
                                  child: Padding(
                                    padding: EdgeInsets.only(top: 8.0),
                                    child: Text.rich(
                                      TextSpan(
                                        text: 'I agree to the ',
                                        style: TextStyle(fontFamily: 'Inter', fontSize: 14, color: Color(0xFF464554), height: 1.5),
                                        children: [
                                          TextSpan(text: 'SnapBid Terms of Service', style: TextStyle(color: Color(0xFF4f46e5), fontWeight: FontWeight.w600, decoration: TextDecoration.underline)),
                                          TextSpan(text: ' and confirm that all information provided is accurate and I have the right to sell this item.'),
                                        ],
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 24),
                            SizedBox(
                              width: double.infinity,
                              height: 56,
                              child: ElevatedButton(
                                onPressed: _isLoading ? null : _publishListing,
                                style: ElevatedButton.styleFrom(
                                  backgroundColor: const Color(0xFF4648d4),
                                  foregroundColor: Colors.white,
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                  elevation: 8,
                                  shadowColor: const Color(0xFF4648d4).withOpacity(0.5),
                                ),
                                child: _isLoading 
                                    ? const SizedBox(
                                        width: 24,
                                        height: 24,
                                        child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2),
                                      ) 
                                    : const Row(
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        children: [
                                          Text('List Item', style: TextStyle(fontFamily: 'Inter', fontSize: 16, fontWeight: FontWeight.w600)),
                                          SizedBox(width: 8),
                                          Icon(Icons.send_rounded, size: 20),
                                        ],
                                      ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ]),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
