import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../core/constants/app_colors.dart';
import '../../core/constants/app_constants.dart';
import '../../core/constants/app_text_styles.dart';
import '../../core/widgets/glass_card.dart';
import '../../core/widgets/app_buttons.dart';
import '../../core/widgets/app_text_field.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../auctions/models/auction_model.dart';
import '../auctions/repositories/auction_repository.dart';
import '../auth/controllers/auth_controller.dart';

class CreateListingScreen extends ConsumerStatefulWidget {
  const CreateListingScreen({super.key});

  @override
  ConsumerState<CreateListingScreen> createState() => _CreateListingScreenState();
}

class _CreateListingScreenState extends ConsumerState<CreateListingScreen> {
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _startingPriceController = TextEditingController();
  final _reservePriceController = TextEditingController();
  String _selectedCategory = 'Timepieces';
  String _selectedDuration = '7 days';
  bool _isLoading = false;

  final List<String> _categories = ['Timepieces', 'Jewelry', 'Fine Art', 'Automotive', 'Collectibles', 'Books', 'Fashion'];
  final List<String> _durations = ['1 day', '3 days', '5 days', '7 days', '10 days', '14 days'];

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _startingPriceController.dispose();
    _reservePriceController.dispose();
    super.dispose();
  }

  Future<void> _publishListing() async {
    if (_titleController.text.isEmpty || _startingPriceController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please fill all required fields.')));
      return;
    }

    setState(() => _isLoading = true);
    try {
      final user = ref.read(authControllerProvider).value;
      if (user == null) throw Exception('Not logged in');

      final days = int.parse(_selectedDuration.split(' ')[0]);
      final endTime = DateTime.now().add(Duration(days: days));

      final auction = AuctionModel(
        id: '', // Will be generated by Appwrite
        title: _titleController.text,
        subtitle: _selectedCategory,
        category: _selectedCategory,
        description: _descriptionController.text.isNotEmpty ? _descriptionController.text : 'No description provided.',
        imageEmoji: '📦',
        currentBid: int.tryParse(_startingPriceController.text) ?? 0,
        totalBids: 0,
        status: 'active',
        endTime: endTime,
        sellerId: user.$id,
        sellerName: user.name,
      );

      await ref.read(auctionRepositoryProvider).createAuction(auction);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('🎉 Listing published successfully!'),
            backgroundColor: AppColors.secondary,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(AppConstants.radiusMD)),
          ),
        );
        context.go('/home');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: Colors.white.withAlpha(230),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close_rounded),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text('Create Listing', style: AppTextStyles.titleLarge),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppConstants.spaceLG),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // ── Image Upload ─────────────────────────────────────────────────
            Text('Photos', style: AppTextStyles.titleMedium),
            const SizedBox(height: AppConstants.spaceSM),
            GlassCard(
              padding: const EdgeInsets.all(AppConstants.spaceLG),
              child: Column(
                children: [
                  Container(
                    height: 140,
                    decoration: BoxDecoration(
                      color: AppColors.primaryFixed,
                      borderRadius: BorderRadius.circular(AppConstants.radiusMD),
                      border: Border.all(color: AppColors.primary.withAlpha(80), width: 2, style: BorderStyle.solid),
                    ),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(Icons.add_photo_alternate_outlined, size: 40, color: AppColors.primary.withAlpha(150)),
                        const SizedBox(height: AppConstants.spaceSM),
                        Text('Tap to add photos', style: AppTextStyles.bodyMedium.copyWith(color: AppColors.primary)),
                        Text('Up to 10 photos • JPG, PNG, WEBP', style: AppTextStyles.labelSmall.copyWith(color: AppColors.onSurfaceVariant)),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            const SizedBox(height: AppConstants.spaceLG),

            // ── Item Details ─────────────────────────────────────────────────
            Text('Item Details', style: AppTextStyles.titleMedium),
            const SizedBox(height: AppConstants.spaceSM),
            GlassCard(
              child: Column(
                children: [
                  AppTextField(
                    label: 'Item Title',
                    hint: 'e.g. Patek Philippe Nautilus 5711',
                    controller: _titleController,
                    prefixIcon: const Icon(Icons.title_rounded, color: AppColors.outline),
                  ),
                  const SizedBox(height: AppConstants.spaceMD),
                  AppTextField(
                    label: 'Description',
                    hint: 'Describe your item in detail…',
                    controller: _descriptionController,
                    maxLines: 4,
                  ),
                  const SizedBox(height: AppConstants.spaceMD),
                  // Category dropdown
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Category', style: AppTextStyles.labelMedium.copyWith(color: AppColors.onSurfaceVariant)),
                      const SizedBox(height: AppConstants.spaceSM),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: AppConstants.spaceMD),
                        decoration: BoxDecoration(
                          color: Colors.white.withAlpha(150),
                          borderRadius: BorderRadius.circular(AppConstants.radiusSM),
                          border: Border.all(color: AppColors.outlineVariant.withAlpha(120)),
                        ),
                        child: DropdownButtonHideUnderline(
                          child: DropdownButton<String>(
                            value: _selectedCategory,
                            isExpanded: true,
                            style: AppTextStyles.bodyMedium,
                            icon: const Icon(Icons.keyboard_arrow_down_rounded, color: AppColors.outline),
                            items: _categories.map((c) => DropdownMenuItem(value: c, child: Text(c))).toList(),
                            onChanged: (v) => setState(() => _selectedCategory = v ?? _selectedCategory),
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),

            const SizedBox(height: AppConstants.spaceLG),

            // ── Pricing ──────────────────────────────────────────────────────
            Text('Pricing', style: AppTextStyles.titleMedium),
            const SizedBox(height: AppConstants.spaceSM),
            GlassCard(
              child: Column(
                children: [
                  AppTextField(
                    label: 'Starting Price (USD)',
                    hint: '0.00',
                    controller: _startingPriceController,
                    keyboardType: TextInputType.number,
                    prefixIcon: const Icon(Icons.attach_money_rounded, color: AppColors.outline),
                  ),
                  const SizedBox(height: AppConstants.spaceMD),
                  AppTextField(
                    label: 'Reserve Price (Optional)',
                    hint: 'Minimum acceptable price',
                    controller: _reservePriceController,
                    keyboardType: TextInputType.number,
                    prefixIcon: const Icon(Icons.price_check_rounded, color: AppColors.outline),
                  ),
                ],
              ),
            ),

            const SizedBox(height: AppConstants.spaceLG),

            // ── Duration ─────────────────────────────────────────────────────
            Text('Auction Duration', style: AppTextStyles.titleMedium),
            const SizedBox(height: AppConstants.spaceSM),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: _durations.map((d) {
                final isSelected = _selectedDuration == d;
                return GestureDetector(
                  onTap: () => setState(() => _selectedDuration = d),
                  child: AnimatedContainer(
                    duration: AppConstants.animFast,
                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                    decoration: BoxDecoration(
                      gradient: isSelected
                          ? const LinearGradient(colors: [AppColors.primaryDark, AppColors.primary])
                          : null,
                      color: isSelected ? null : Colors.white.withAlpha(200),
                      borderRadius: BorderRadius.circular(AppConstants.radiusSM),
                      border: Border.all(
                        color: isSelected ? AppColors.primary : AppColors.outlineVariant.withAlpha(80),
                      ),
                    ),
                    child: Text(
                      d,
                      style: AppTextStyles.labelMedium.copyWith(
                        color: isSelected ? AppColors.onPrimary : AppColors.onSurface,
                      ),
                    ),
                  ),
                );
              }).toList(),
            ),

            const SizedBox(height: AppConstants.spaceXL),

            PrimaryButton(
              label: 'Publish Listing',
              icon: Icons.rocket_launch_rounded,
              isLoading: _isLoading,
              onPressed: _publishListing,
            ),

            const SizedBox(height: AppConstants.spaceLG),
          ],
        ),
      ),
    );
  }
}
