import 'dart:io';
import 'dart:ui';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../auctions/models/auction_model.dart';
import '../auctions/repositories/auction_repository.dart';
import '../auctions/controllers/auction_controller.dart';
import '../auth/controllers/auth_controller.dart';

class CreateListingScreen extends ConsumerStatefulWidget {
  final String category;
  final String? subCategory;
  final String? model;

  const CreateListingScreen({
    super.key,
    required this.category,
    this.subCategory,
    this.model,
  });

  @override
  ConsumerState<CreateListingScreen> createState() => _CreateListingScreenState();
}

class _CreateListingScreenState extends ConsumerState<CreateListingScreen> {
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _startingPriceController = TextEditingController();
  DateTime? _selectedEndTime;
  bool _isLoading = false;
  bool _acceptedTerms = false;
  
  final _picker = ImagePicker();
  List<XFile> _selectedImages = [];



  Future<void> _pickEndTime() async {
    final DateTime? date = await showDatePicker(
      context: context,
      initialDate: DateTime.now().add(const Duration(days: 1)),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );
    if (date != null && mounted) {
      final TimeOfDay? time = await showTimePicker(
        context: context,
        initialTime: TimeOfDay.now(),
      );
      if (time != null) {
        setState(() {
          _selectedEndTime = DateTime(
            date.year,
            date.month,
            date.day,
            time.hour,
            time.minute,
          );
        });
      }
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _startingPriceController.dispose();
    super.dispose();
  }

  Future<void> _pickImages() async {
    try {
      final List<XFile> images = await _picker.pickMultiImage(imageQuality: 80);
      if (images.isNotEmpty) {
        setState(() {
          if (_selectedImages.length + images.length > 10) {
            _selectedImages.addAll(images.take(10 - _selectedImages.length));
            ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Maximum 10 images allowed.')));
          } else {
            _selectedImages.addAll(images);
          }
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error picking images: $e')));
      }
    }
  }

  void _removeImage(int index) {
    setState(() {
      _selectedImages.removeAt(index);
    });
  }

  Future<void> _publishListing() async {
    if (_titleController.text.isEmpty || _startingPriceController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please fill all required fields.')));
      return;
    }
    if (_selectedEndTime == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select an auction end time.')));
      return;
    }
    if (_selectedImages.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select at least one photo.')));
      return;
    }
    if (!_acceptedTerms) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please accept the terms to continue.')));
      return;
    }

    setState(() => _isLoading = true);
    try {
      final user = ref.read(authControllerProvider).value;
      if (user == null) throw Exception('Not logged in');

      String? imageUrl;
      List<String> uploadedUrls = [];
      if (_selectedImages.isNotEmpty) {
        for (var img in _selectedImages) {
          final bytes = await img.readAsBytes();
          final url = await ref.read(auctionRepositoryProvider).uploadImage(bytes, img.name);
          uploadedUrls.add(url);
        }
        if (uploadedUrls.isNotEmpty) imageUrl = uploadedUrls.first;
      }

      final endTime = _selectedEndTime!;

      final auction = AuctionModel(
        id: '', // Will be generated by Appwrite
        createdAt: DateTime.now(),
        title: _titleController.text,
        subtitle: widget.subCategory ?? widget.category,
        category: widget.category,
        subCategory: widget.subCategory,
        description: _descriptionController.text.isNotEmpty ? _descriptionController.text : 'No description provided.',
        imageEmoji: '📦',
        imageUrl: imageUrl,
        imageUrls: uploadedUrls,
        currentBid: int.tryParse(_startingPriceController.text) ?? 0,
        totalBids: 0,
        status: 'active',
        endTime: endTime,
        sellerId: user.$id,
        sellerName: user.name,
      );

      await ref.read(auctionRepositoryProvider).createAuction(auction);

      ref.invalidate(recentAuctionsProvider);
      ref.invalidate(trendingAuctionsProvider);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('🎉 Listing published successfully!'),
            backgroundColor: const Color(0xFF006c49),
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
          ),
        );
        context.go('/home');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Widget _buildCardPanel({required Widget child}) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFE5E7EB)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Padding(
        padding: const EdgeInsets.all(24.0),
        child: child,
      ),
    );
  }

  Widget _buildSectionTitle(IconData icon, String title) {
    return Row(
      children: [
        Icon(icon, color: const Color(0xFF4648d4), size: 24),
        const SizedBox(width: 8),
        Text(
          title,
          style: const TextStyle(
            fontFamily: 'Manrope',
            fontSize: 24,
            fontWeight: FontWeight.w700,
            color: Color(0xFF1b1b23),
          ),
        ),
      ],
    );
  }

  Widget _buildInputLabel(String label) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 4.0),
      child: Text(
        label,
        style: const TextStyle(
          fontFamily: 'Inter',
          fontSize: 14,
          fontWeight: FontWeight.w600,
          color: Color(0xFF464554),
        ),
      ),
    );
  }

  InputDecoration _inputDecoration(String hint, {Widget? prefixIcon}) {
    return InputDecoration(
      hintText: hint,
      hintStyle: const TextStyle(color: Color(0xFF767586), fontFamily: 'Inter'),
      prefixIcon: prefixIcon,
      filled: true,
      fillColor: Colors.white,
      contentPadding: const EdgeInsets.all(16),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: const BorderSide(color: Color(0xFFE5E7EB)),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: const BorderSide(color: Color(0xFFE5E7EB)),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: const BorderSide(color: Color(0xFF4648d4), width: 1.5),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF3F4F6),
      body: Stack(
        children: [
          
          SafeArea(
            child: CustomScrollView(
              slivers: [
                SliverAppBar(
                  backgroundColor: Colors.white,
                  pinned: true,
                  elevation: 1,
                  shadowColor: Colors.black.withValues(alpha: 0.1),
                  leading: IconButton(
                    icon: const Icon(Icons.close_rounded, color: Color(0xFF1b1b23)),
                    onPressed: () {
                      if (context.canPop()) {
                        context.pop();
                      } else {
                        context.go('/home');
                      }
                    },
                  ),
                  title: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      const Icon(Icons.gavel, color: Color(0xFF4648d4), size: 24),
                      const SizedBox(width: 8),
                      const Text(
                        'Post an Ad',
                        style: TextStyle(
                          fontFamily: 'Manrope',
                          fontSize: 20,
                          fontWeight: FontWeight.w800,
                          color: Color(0xFF1b1b23),
                          letterSpacing: -0.5,
                        ),
                      ),
                    ],
                  ),
                  centerTitle: true,
                ),
                SliverPadding(
                  padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 32.0),
                  sliver: SliverList(
                    delegate: SliverChildListDelegate([
                      const Text(
                        'Create New Listing',
                        style: TextStyle(
                          fontFamily: 'Manrope',
                          fontSize: 32,
                          fontWeight: FontWeight.w700,
                          color: Color(0xFF1b1b23),
                        ),
                      ),
                      const SizedBox(height: 8),
                      const Text(
                        'Fill in the details to showcase your item to thousands of bidders.',
                        style: TextStyle(
                          fontFamily: 'Inter',
                          fontSize: 16,
                          color: Color(0xFF464554),
                        ),
                      ),
                      const SizedBox(height: 32),

                      // Section 1: Photos
                      _buildCardPanel(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                _buildSectionTitle(Icons.photo_library_outlined, 'Photos'),
                                Text(
                                  '${_selectedImages.length} / 10 Images',
                                  style: const TextStyle(
                                    fontFamily: 'Inter',
                                    fontSize: 14,
                                    color: Color(0xFF767586),
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 16),
                            if (_selectedImages.isEmpty)
                              GestureDetector(
                                onTap: _pickImages,
                                child: Container(
                                  height: 200,
                                  width: double.infinity,
                                  decoration: BoxDecoration(
                                    color: Colors.white,
                                    borderRadius: BorderRadius.circular(8),
                                    border: Border.all(
                                      color: const Color(0xFFE5E7EB),
                                      style: BorderStyle.solid,
                                      width: 1,
                                    ),
                                  ),
                                  child: const Column(
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    children: [
                                      Icon(Icons.add_photo_alternate_outlined, size: 40, color: Color(0xFF767586)),
                                      SizedBox(height: 8),
                                      Text(
                                        'Add Main Photo',
                                        style: TextStyle(
                                          fontFamily: 'Inter',
                                          fontSize: 14,
                                          fontWeight: FontWeight.w600,
                                          color: Color(0xFF767586),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              )
                            else
                              Column(
                                children: [
                                  Container(
                                    height: 200,
                                    width: double.infinity,
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(8),
                                      image: DecorationImage(
                                        image: kIsWeb
                                            ? NetworkImage(_selectedImages.first.path)
                                            : FileImage(File(_selectedImages.first.path)) as ImageProvider,
                                        fit: BoxFit.cover,
                                      ),
                                    ),
                                    child: Align(
                                      alignment: Alignment.topRight,
                                      child: IconButton(
                                        icon: Container(
                                          padding: const EdgeInsets.all(4),
                                          decoration: const BoxDecoration(color: Colors.black54, shape: BoxShape.circle),
                                          child: const Icon(Icons.close, color: Colors.white, size: 16),
                                        ),
                                        onPressed: () => _removeImage(0),
                                      ),
                                    ),
                                  ),
                                  if (_selectedImages.length > 1 || _selectedImages.length < 10)
                                    Padding(
                                      padding: const EdgeInsets.only(top: 16.0),
                                      child: SizedBox(
                                        height: 80,
                                        child: ListView.builder(
                                          scrollDirection: Axis.horizontal,
                                          itemCount: (_selectedImages.length - 1) + (_selectedImages.length < 10 ? 1 : 0),
                                          itemBuilder: (context, index) {
                                            if (index == _selectedImages.length - 1 && _selectedImages.length < 10) {
                                              return GestureDetector(
                                                onTap: _pickImages,
                                                child: Container(
                                                  width: 80,
                                                  margin: const EdgeInsets.only(right: 8),
                                                  decoration: BoxDecoration(
                                                    color: Colors.white,
                                                    borderRadius: BorderRadius.circular(8),
                                                    border: Border.all(color: const Color(0xFFE5E7EB), width: 1),
                                                  ),
                                                  child: const Icon(Icons.add, color: Color(0xFF767586)),
                                                ),
                                              );
                                            }
                                            final imgIndex = index + 1;
                                            return Container(
                                              width: 80,
                                              margin: const EdgeInsets.only(right: 8),
                                              decoration: BoxDecoration(
                                                borderRadius: BorderRadius.circular(8),
                                                image: DecorationImage(
                                                  image: kIsWeb
                                                      ? NetworkImage(_selectedImages[imgIndex].path)
                                                      : FileImage(File(_selectedImages[imgIndex].path)) as ImageProvider,
                                                  fit: BoxFit.cover,
                                                ),
                                              ),
                                              child: Align(
                                                alignment: Alignment.topRight,
                                                child: GestureDetector(
                                                  onTap: () => _removeImage(imgIndex),
                                                  child: Container(
                                                    margin: const EdgeInsets.all(4),
                                                    padding: const EdgeInsets.all(2),
                                                    decoration: const BoxDecoration(color: Colors.black54, shape: BoxShape.circle),
                                                    child: const Icon(Icons.close, color: Colors.white, size: 12),
                                                  ),
                                                ),
                                              ),
                                            );
                                          },
                                        ),
                                      ),
                                    ),
                                ],
                              ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),

                      // Section 2: Item Basics
                      _buildCardPanel(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _buildSectionTitle(Icons.edit_note_outlined, 'Item Basics'),
                            const SizedBox(height: 24),
                            _buildInputLabel('Listing Title'),
                            TextField(
                              controller: _titleController,
                              style: const TextStyle(fontFamily: 'Inter', fontSize: 16, color: Color(0xFF1b1b23)),
                              decoration: _inputDecoration('e.g. Rare 1964 Vintage Chronograph'),
                            ),
                            const SizedBox(height: 16),
                            _buildInputLabel('Selected Category'),
                            Container(
                              width: double.infinity,
                              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                              decoration: BoxDecoration(
                                color: Colors.white.withValues(alpha: 0.8),
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(color: const Color(0xFFc7c4d7), width: 1),
                              ),
                              child: Row(
                                children: [
                                  Expanded(
                                    child: Column(
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Text(
                                          [
                                            widget.category,
                                            if (widget.subCategory != null) widget.subCategory!,
                                            if (widget.model != null) widget.model!
                                          ].join(' > '),
                                          style: const TextStyle(
                                            fontFamily: 'Inter',
                                            color: Color(0xFF1b1b23),
                                            fontSize: 16,
                                            fontWeight: FontWeight.w600,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  GestureDetector(
                                    onTap: () {
                                      // Pop back to re-select
                                      context.pop();
                                      if (widget.subCategory != null) {
                                        context.pop();
                                      }
                                      if (widget.model != null) {
                                        context.pop();
                                      }
                                    },
                                    child: Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                                      decoration: BoxDecoration(
                                        color: const Color(0xFFe1e0ff),
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                      child: const Text('Change', style: TextStyle(color: Color(0xFF4648d4), fontWeight: FontWeight.bold, fontFamily: 'Inter', fontSize: 12)),
                                    ),
                                  )
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),

                      // Section 3: Description
                      _buildCardPanel(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _buildSectionTitle(Icons.description_outlined, 'Description'),
                            const SizedBox(height: 16),
                            _buildInputLabel('Item Details'),
                            TextField(
                              controller: _descriptionController,
                              maxLines: 5,
                              style: const TextStyle(fontFamily: 'Inter', fontSize: 16, color: Color(0xFF1b1b23)),
                              decoration: _inputDecoration('Describe your item in detail...'),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),

                      // Section 4: Auction Settings
                      _buildCardPanel(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _buildSectionTitle(Icons.payments_outlined, 'Auction Settings'),
                            const SizedBox(height: 24),
                            _buildInputLabel('Starting Price (PKR)'),
                            TextField(
                              controller: _startingPriceController,
                              keyboardType: TextInputType.number,
                              style: const TextStyle(fontFamily: 'Inter', fontSize: 16, color: Color(0xFF1b1b23)),
                              decoration: _inputDecoration('0.00', prefixIcon: const Padding(
                                padding: EdgeInsets.only(left: 16.0, right: 8.0),
                                child: Text('PKR ', style: TextStyle(fontFamily: 'Inter', fontSize: 16, fontWeight: FontWeight.bold, color: Color(0xFF767586))),
                              )).copyWith(prefixIconConstraints: const BoxConstraints(minWidth: 0, minHeight: 0)),
                            ),
                            _buildInputLabel('Auction End Time'),
                            GestureDetector(
                              onTap: _pickEndTime,
                              child: Container(
                                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                                decoration: BoxDecoration(
                                  color: Colors.white,
                                  borderRadius: BorderRadius.circular(8),
                                  border: Border.all(color: const Color(0xFFE5E7EB)),
                                ),
                                child: Row(
                                  children: [
                                    const Icon(Icons.calendar_month_outlined, color: Color(0xFF767586)),
                                    const SizedBox(width: 12),
                                    Text(
                                      _selectedEndTime == null
                                          ? 'Select Date & Time'
                                          : '${_selectedEndTime!.day}/${_selectedEndTime!.month}/${_selectedEndTime!.year} at ${_selectedEndTime!.hour}:${_selectedEndTime!.minute.toString().padLeft(2, '0')}',
                                      style: TextStyle(
                                        fontFamily: 'Inter',
                                        fontSize: 16,
                                        color: _selectedEndTime == null ? const Color(0xFF767586) : const Color(0xFF1b1b23),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),

                      // Terms and Submission
                      Padding(
                        padding: const EdgeInsets.only(top: 16.0, bottom: 48.0),
                        child: Column(
                          children: [
                            Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Checkbox(
                                  value: _acceptedTerms,
                                  onChanged: (v) => setState(() => _acceptedTerms = v ?? false),
                                  activeColor: const Color(0xFF4648d4),
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                ),
                                const Expanded(
                                  child: Padding(
                                    padding: EdgeInsets.only(top: 8.0),
                                    child: Text.rich(
                                      TextSpan(
                                        text: 'I agree to the ',
                                        style: TextStyle(fontFamily: 'Inter', fontSize: 14, color: Color(0xFF464554), height: 1.5),
                                        children: [
                                          TextSpan(text: 'SnapBid Terms of Service', style: TextStyle(color: Color(0xFF4f46e5), fontWeight: FontWeight.w600, decoration: TextDecoration.underline)),
                                          TextSpan(text: ' and confirm that all information provided is accurate and I have the right to sell this item.'),
                                        ],
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 24),
                            SizedBox(
                              width: double.infinity,
                              height: 56,
                              child: ElevatedButton(
                                onPressed: _isLoading ? null : _publishListing,
                                style: ElevatedButton.styleFrom(
                                  backgroundColor: const Color(0xFF4648d4),
                                  foregroundColor: Colors.white,
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                  elevation: 8,
                                  shadowColor: const Color(0xFF4648d4).withOpacity(0.5),
                                ),
                                child: _isLoading 
                                    ? const SizedBox(
                                        width: 24,
                                        height: 24,
                                        child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2),
                                      ) 
                                    : const Row(
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        children: [
                                          Text('List Item', style: TextStyle(fontFamily: 'Inter', fontSize: 16, fontWeight: FontWeight.w600)),
                                          SizedBox(width: 8),
                                          Icon(Icons.send_rounded, size: 20),
                                        ],
                                      ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ]),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
